# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'starshipMainWindow.ui'
#
# Created: Thu Mar 21 20:18:42 2013
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_StarshipMainWindow(object):
    def setupUi(self, StarshipMainWindow):
        StarshipMainWindow.setObjectName("StarshipMainWindow")
        StarshipMainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(StarshipMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setMargin(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hexView = HexTileGraphicsView(self.centralwidget)
        self.hexView.setDragMode(QtGui.QGraphicsView.RubberBandDrag)
        self.hexView.setResizeAnchor(QtGui.QGraphicsView.AnchorViewCenter)
        self.hexView.setObjectName("hexView")
        self.horizontalLayout.addWidget(self.hexView)
        StarshipMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(StarshipMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSimulation = QtGui.QMenu(self.menubar)
        self.menuSimulation.setObjectName("menuSimulation")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuBuild = QtGui.QMenu(self.menubar)
        self.menuBuild.setEnabled(True)
        self.menuBuild.setObjectName("menuBuild")
        StarshipMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(StarshipMainWindow)
        self.statusbar.setObjectName("statusbar")
        StarshipMainWindow.setStatusBar(self.statusbar)
        self.simulationParameters = QtGui.QDockWidget(StarshipMainWindow)
        self.simulationParameters.setObjectName("simulationParameters")
        self.simulationDockContents = DockContentsWidget()
        self.simulationDockContents.setObjectName("simulationDockContents")
        self.layoutWidget = QtGui.QWidget(self.simulationDockContents)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 289, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.simRateLabel = QtGui.QLabel(self.layoutWidget)
        self.simRateLabel.setObjectName("simRateLabel")
        self.verticalLayout.addWidget(self.simRateLabel)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.simRateBaseLabel = QtGui.QLabel(self.layoutWidget)
        self.simRateBaseLabel.setObjectName("simRateBaseLabel")
        self.horizontalLayout_2.addWidget(self.simRateBaseLabel)
        self.simRateLimit = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.simRateLimit.setEnabled(True)
        self.simRateLimit.setMinimum(-99.0)
        self.simRateLimit.setMaximum(99.99)
        self.simRateLimit.setSingleStep(0.1)
        self.simRateLimit.setObjectName("simRateLimit")
        self.horizontalLayout_2.addWidget(self.simRateLimit)
        self.simRateLimitUnitsLabel = QtGui.QLabel(self.layoutWidget)
        self.simRateLimitUnitsLabel.setObjectName("simRateLimitUnitsLabel")
        self.horizontalLayout_2.addWidget(self.simRateLimitUnitsLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.frameRateLabel = QtGui.QLabel(self.layoutWidget)
        self.frameRateLabel.setObjectName("frameRateLabel")
        self.verticalLayout.addWidget(self.frameRateLabel)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.frameRateLimit = QtGui.QSpinBox(self.layoutWidget)
        self.frameRateLimit.setMaximum(999)
        self.frameRateLimit.setSingleStep(15)
        self.frameRateLimit.setProperty("value", 30)
        self.frameRateLimit.setObjectName("frameRateLimit")
        self.horizontalLayout_3.addWidget(self.frameRateLimit)
        self.frameRateUnitsLabel = QtGui.QLabel(self.layoutWidget)
        self.frameRateUnitsLabel.setObjectName("frameRateUnitsLabel")
        self.horizontalLayout_3.addWidget(self.frameRateUnitsLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.simulationParameters.setWidget(self.simulationDockContents)
        StarshipMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.simulationParameters)
        self.actionQuit = QtGui.QAction(StarshipMainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtGui.QAction(StarshipMainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAboutQt = QtGui.QAction(StarshipMainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.actionSimRunning = QtGui.QAction(StarshipMainWindow)
        self.actionSimRunning.setCheckable(True)
        self.actionSimRunning.setChecked(True)
        self.actionSimRunning.setObjectName("actionSimRunning")
        self.actionStatusBar = QtGui.QAction(StarshipMainWindow)
        self.actionStatusBar.setCheckable(True)
        self.actionStatusBar.setChecked(True)
        self.actionStatusBar.setObjectName("actionStatusBar")
        self.actionFullscreen = QtGui.QAction(StarshipMainWindow)
        self.actionFullscreen.setCheckable(True)
        self.actionFullscreen.setObjectName("actionFullscreen")
        self.actionSimulationParameters = QtGui.QAction(StarshipMainWindow)
        self.actionSimulationParameters.setCheckable(True)
        self.actionSimulationParameters.setChecked(True)
        self.actionSimulationParameters.setObjectName("actionSimulationParameters")
        self.actionBuildDeck = QtGui.QAction(StarshipMainWindow)
        self.actionBuildDeck.setEnabled(True)
        self.actionBuildDeck.setObjectName("actionBuildDeck")
        self.actionBuildBulkhead = QtGui.QAction(StarshipMainWindow)
        self.actionBuildBulkhead.setObjectName("actionBuildBulkhead")
        self.actionUnbuild = QtGui.QAction(StarshipMainWindow)
        self.actionUnbuild.setObjectName("actionUnbuild")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAboutQt)
        self.menuSimulation.addAction(self.actionSimRunning)
        self.menuSimulation.addAction(self.actionSimulationParameters)
        self.menuView.addAction(self.actionStatusBar)
        self.menuView.addAction(self.actionFullscreen)
        self.menuBuild.addAction(self.actionBuildDeck)
        self.menuBuild.addAction(self.actionBuildBulkhead)
        self.menuBuild.addSeparator()
        self.menuBuild.addAction(self.actionUnbuild)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuBuild.menuAction())
        self.menubar.addAction(self.menuSimulation.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(StarshipMainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("triggered()"), StarshipMainWindow.close)
        QtCore.QObject.connect(self.actionStatusBar, QtCore.SIGNAL("toggled(bool)"), self.statusbar.setVisible)
        QtCore.QObject.connect(self.actionSimulationParameters, QtCore.SIGNAL("toggled(bool)"), self.simulationParameters.setVisible)
        QtCore.QObject.connect(self.simulationParameters, QtCore.SIGNAL("visibilityChanged(bool)"), self.actionSimulationParameters.setChecked)
        QtCore.QMetaObject.connectSlotsByName(StarshipMainWindow)

    def retranslateUi(self, StarshipMainWindow):
        StarshipMainWindow.setWindowTitle(QtGui.QApplication.translate("StarshipMainWindow", "Starship", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("StarshipMainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("StarshipMainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSimulation.setTitle(QtGui.QApplication.translate("StarshipMainWindow", "&Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("StarshipMainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBuild.setTitle(QtGui.QApplication.translate("StarshipMainWindow", "&Build", None, QtGui.QApplication.UnicodeUTF8))
        self.simulationParameters.setWindowTitle(QtGui.QApplication.translate("StarshipMainWindow", "Simulation Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.simRateLabel.setText(QtGui.QApplication.translate("StarshipMainWindow", "Limit simulation rate to:", None, QtGui.QApplication.UnicodeUTF8))
        self.simRateBaseLabel.setText(QtGui.QApplication.translate("StarshipMainWindow", "60^", None, QtGui.QApplication.UnicodeUTF8))
        self.simRateLimitUnitsLabel.setText(QtGui.QApplication.translate("StarshipMainWindow", "seconds per second", None, QtGui.QApplication.UnicodeUTF8))
        self.frameRateLabel.setText(QtGui.QApplication.translate("StarshipMainWindow", "Limit frame rate to:", None, QtGui.QApplication.UnicodeUTF8))
        self.frameRateUnitsLabel.setText(QtGui.QApplication.translate("StarshipMainWindow", "frames per second", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("StarshipMainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setStatusTip(QtGui.QApplication.translate("StarshipMainWindow", "Exit this application", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("StarshipMainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("StarshipMainWindow", "&About Starship", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setStatusTip(QtGui.QApplication.translate("StarshipMainWindow", "Display Starship version and copyright", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutQt.setText(QtGui.QApplication.translate("StarshipMainWindow", "About &Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutQt.setStatusTip(QtGui.QApplication.translate("StarshipMainWindow", "Display Qt version and copyright", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimRunning.setText(QtGui.QApplication.translate("StarshipMainWindow", "&Running", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimRunning.setStatusTip(QtGui.QApplication.translate("StarshipMainWindow", "Pause or resume the flow of time", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimRunning.setShortcut(QtGui.QApplication.translate("StarshipMainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStatusBar.setText(QtGui.QApplication.translate("StarshipMainWindow", "&Status Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStatusBar.setStatusTip(QtGui.QApplication.translate("StarshipMainWindow", "Toggle visibility of this status bar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFullscreen.setText(QtGui.QApplication.translate("StarshipMainWindow", "&Fullscreen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFullscreen.setShortcut(QtGui.QApplication.translate("StarshipMainWindow", "F11", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimulationParameters.setText(QtGui.QApplication.translate("StarshipMainWindow", "&Parameters panel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuildDeck.setText(QtGui.QApplication.translate("StarshipMainWindow", "&Deck", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuildBulkhead.setText(QtGui.QApplication.translate("StarshipMainWindow", "&Bulkhead", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnbuild.setText(QtGui.QApplication.translate("StarshipMainWindow", "&Un-build", None, QtGui.QApplication.UnicodeUTF8))

from dockcontentswidget import DockContentsWidget
from hextilegraphicsview import HexTileGraphicsView
